Upgrade rust to `1.81.0` (#14330)
### Notable Changes
- Fixed lint warnings by changing the code for
- [`clippy::manual_unwrap_or`](https://rust-lang.github.io/rust-clippy/master/index.html#manual_unwrap_or)
- [`clippy::manual_unwrap_or_default`](https://rust-lang.github.io/rust-clippy/master/index.html#manual_unwrap_or_default)
- [`clippy::manual_inspect`](https://rust-lang.github.io/rust-clippy/master/index.html#manual_inspect)
- [`clippy::manual_rotate`](https://rust-lang.github.io/rust-clippy/master/index.html#/manual_rotate)
- [`clippy::needless_borrows_for_generic_args`](https://rust-lang.github.io/rust-clippy/master/index.html#/needless_borrows_for_generic_args)
- [`dependency_on_unit_never_type_fallback`](https://github.com/rust-lang/rust/issues/123748)
- [`clippy::needless_borrow`](https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow)
- Fix lint warning by allowing
- [`clippy::needless_maybe_sized`](https://rust-lang.github.io/rust-clippy/master/index.html#/needless_maybe_sized)
- Bump autometrics to 1.0.1
- Remove `clippy::mismatched_target_os lint` as it has been replaced by `unexpected_cfgs`
- Fix `dead_code` warning on android

The choice of allowed in wim-app/components/noesis-cxx/src/ffi.rs might need some extra eyes @rib, the original error was this:
```
error: `?Sized` bound is ignored because of a `Sized` requirement
--> components/noesis-cxx/src/ffi.rs:121:14
|
121 | type Responder;
| ^^^^^^^^^^
|
note: `T` cannot be unsized because of the bound
--> components/noesis-cxx/src/ffi.rs:121:9
|
121 | type Responder;
| ^^^^^^^^^^^^^^^
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_maybe_sized
= note: `-D clippy::needless-maybe-sized` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(clippy::needless_maybe_sized)]`
help: change the bounds that require `Sized`, or remove the `?Sized` bound
|
121 - type Responder;
|
```

https://github.com/EmbarkStudios/wim-app/pull/14330